-- Two-layer regime architecture persistence.
-- Layer 1 model artifacts may remain as JSON files; this migration stores the
-- per-stock model contract and every final allocation result for auditability.

create table if not exists public.stock_risk_models (
    id bigint generated by default as identity primary key,
    ticker text not null,
    model_version text not null,
    schema_version integer not null,
    model_type text not null default 'StockRiskModel',
    market_model_version text,
    created_at timestamptz not null,
    config jsonb not null,
    unique (ticker, model_version)
);

create index if not exists idx_stock_risk_models_ticker_created
    on public.stock_risk_models (ticker, created_at desc);

create table if not exists public.allocation_results (
    id bigint generated by default as identity primary key,
    result_timestamp timestamptz not null,
    ticker text not null,
    market_regime text not null,
    market_regime_probability double precision not null,
    base_multiplier double precision not null,
    relative_vol double precision not null,
    beta double precision not null,
    vol_scalar double precision not null,
    final_multiplier double precision not null,
    is_regime_confirmed boolean not null default false,
    is_flickering boolean not null default false,
    reasoning text,
    created_at timestamptz not null default now()
);

create index if not exists idx_allocation_results_ticker_timestamp
    on public.allocation_results (ticker, result_timestamp desc);

create index if not exists idx_allocation_results_timestamp
    on public.allocation_results (result_timestamp desc);
