-- Two-layer market model and allocation persistence.
-- Strategy/RiskManager and broker execution are intentionally out of scope.

create table if not exists market_regime_models (
    model_version text primary key,
    model_type text not null,
    schema_version integer not null default 1,
    market_ticker text not null,
    training_date timestamptz not null,
    n_states integer not null,
    bic_score double precision not null,
    artifact jsonb not null,
    status text not null default 'ACTIVE',
    created_at timestamptz not null default now()
);

create unique index if not exists uq_market_regime_models_active_ticker
    on market_regime_models (market_ticker)
    where status = 'ACTIVE';

create table if not exists market_regime_results (
    id bigint generated by default as identity primary key,
    result_date date not null,
    market_ticker text not null,
    market_model_version text not null references market_regime_models(model_version),
    state_id integer not null,
    regime_label text not null,
    probability double precision not null,
    state_probabilities jsonb not null,
    base_multiplier double precision not null,
    is_confirmed boolean not null,
    consecutive_bars integer not null,
    is_flickering boolean not null,
    created_at timestamptz not null default now(),
    unique (market_ticker, result_date, market_model_version)
);

create index if not exists idx_market_regime_results_date
    on market_regime_results (result_date desc);

create table if not exists stock_risk_models (
    ticker text not null,
    model_version text not null,
    schema_version integer not null default 1,
    market_model_version text,
    model_type text not null,
    created_at timestamptz not null,
    config jsonb not null,
    primary key (ticker, model_version)
);

create table if not exists allocation_results (
    id bigint generated by default as identity primary key,
    result_timestamp timestamptz not null,
    ticker text not null,
    market_model_version text not null references market_regime_models(model_version),
    stock_model_version text not null,
    market_regime text not null,
    market_regime_probability double precision not null,
    base_multiplier double precision not null,
    relative_vol double precision not null,
    beta double precision not null,
    vol_scalar double precision not null,
    final_multiplier double precision not null,
    is_regime_confirmed boolean not null,
    is_flickering boolean not null,
    reasoning text not null,
    created_at timestamptz not null default now(),
    unique (ticker, result_timestamp, market_model_version, stock_model_version)
);

create index if not exists idx_allocation_results_timestamp
    on allocation_results (result_timestamp desc);

alter table stock_risk_models
    add column if not exists model_type text;
alter table stock_risk_models
    add column if not exists schema_version integer default 1;
alter table stock_risk_models
    add column if not exists market_model_version text;
alter table stock_risk_models
    add column if not exists created_at timestamptz default now();
alter table stock_risk_models
    add column if not exists config jsonb;

alter table allocation_results
    add column if not exists market_model_version text;
alter table allocation_results
    add column if not exists stock_model_version text;

alter table allocation_results
    drop constraint if exists allocation_results_unique_daily;

-- If allocation_results already existed before this migration, the new
-- uniqueness constraint is added separately so retries remain idempotent.
create unique index if not exists uq_allocation_results_logical
    on allocation_results (ticker, result_timestamp, market_model_version, stock_model_version);
